config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'music'   => 'static_pages#music'
  get 'video'   => 'static_pages#video'
  get 'signup'  => 'users#new'

  #get 'sample-artwork'  => 'paintings/2'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'paintings/order'   => 'paintings#order'
  resources :paintings

  get    'illustrations' => 'paintings#illustrations'

  get    'say-hello'   => 'contacts#new'
  resources :contacts

  resources :tags
  resources :users
  resources :account_activations, only: [:edit]

end

app/models/painting.rb
class Painting < ActiveRecord::Base
	# Upload file for cloudinary
	attr_accessor :upload

	has_attached_file :image, styles: { 
		small: "150x150", 
		medium: "300x300>", 
		thumb: "100x100>", 
		large: "600x600>" 
	}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	has_many :taggings
	has_many :tags, through: :taggings

	validates :title,    presence: true
	validates :ordering, presence: true
	validates :upload,   presence: true, if: :new_record?

	before_create do
		begin
			resp = Cloudinary::Uploader.upload(self.upload)
			self.cloudinary_asset_id = resp["public_id"]
		rescue Exception => err
			errors.add(:upload, err.message)
			false
		end
	end

	scope :non_painting_featured, -> { where(painting_featured: false) }

	def tag_list
	  self.tags.collect do |tag|
	    tag.name
	  end.join(", ")
	end

	def tag_list=(tags_string)
	  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
	  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
	  self.tags = new_or_found_tags
	end




end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
	
	include PaintingsHelper
	before_action :logged_in_user, only: [ :edit, :update, :destroy, :new ]
	before_action :admin_user,     only: [ :edit, :update, :destroy, :new ]

	def index
    @paintings  = Painting.all.where(painting_type: "Painting").sort_by &:ordering 
    @paintings2 = Painting.all.where(painting_type: "Commissions").sort_by &:ordering 

    @paintingsFull    = Painting.all.where(painting_type: "Painting").sort_by &:ordering 
    @paintingsFullNon = Painting.all.where(painting_type: "Commissions").sort_by &:ordering 
	end

  def illustrations
    @illustrations = Painting.where(painting_type: "Illustration").order("ordering asc")
  end
  	
	def show
		@painting = Painting.find(params[:id])
	end

	def new
		@painting = Painting.new
	end

	def create
 	  @painting = Painting.new(painting_params)
	  if @painting.save
	    redirect_to painting_path(@painting)
	    flash[:success] = "Painting Added"
    else
      flash[:danger] = "Cant save the painting"
      render :new
    end
	end

	def destroy
		@painting = Painting.find(params[:id])
	    @painting.destroy
	    redirect_to action: "index"		
	end	

	def edit
	  @painting = Painting.find(params[:id])
	end

	def update
	  @painting = Painting.find(params[:id])
	  @painting.update(painting_params)
	  
	  respond_to do |format|
	  	format.html { redirect_to painting_path(@painting) }
	  	format.js #render paintings/update.js.erb
	  end
	  	
	  #redirect_to painting_path(@painting)

	  flash[:success] = "Painting Updated"
	end

	def order

    	@paintings = Painting.all.where(painting_type: "Painting").sort_by &:ordering 
    	@paintings2 = Painting.all.where(painting_type: "Commissions").sort_by &:ordering 
      @illustrations = Painting.where(painting_type: "Illustration").order("ordering asc")

    	@paintingsFull = Painting.all.where(painting_featured: true).sort_by &:ordering 
    	@paintingsFullNon = Painting.all.where(painting_featured: false).sort_by &:ordering 

	end

  private

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end   




end  

app/helpers/paintings_helper.rb
module PaintingsHelper
	def painting_params
		params.require(:painting).permit(
		  :title, :body, :ordering, :painting_type, :painting_featured, :painting_path, :tag_list, :image, :upload
		)
	end
end

app/views/paintings/_form.html.erb
<%= form_for(@painting, html: {multipart: true}) do |f| %>
  <ul>
  <% @painting.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <% if @painting.image.exists? %>

      <%= image_tag @painting.image.url(:thumb) %><br/>
  <% end %>

  <p>
    <%= f.label :upload, "Attach an Image" %><br />
    <%= f.file_field :upload %>
  </p>

<p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list %>
</p>

  <p>
    <%= f.label :ordering %><br />
    <%= f.text_field :ordering %>
  </p>

  <p>
    <%= f.label :painting_featured %>
    <%= f.check_box :painting_featured %>
  </p>

  <p>
    <%= f.label :painting_type %><br />
    <%= f.select :painting_type, ['Painting', 'Commissions', 'Illustration'] %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/paintings/edit.html.erb
<% provide(:title, 'Edit A Painting') %>
<h1>Edit a Painting</h1>

<%= render partial: 'form' %>

app/views/paintings/illustrations.html.erb
<% provide(:title, 'Illustrations') %>

<script type="text/javascript">
  $( "#Illustrations-nav" ).css( "font-weight", "bold" );
</script>

  <div id="art-index" class="container">
    
      <a id="close">Gallery</a>
    

    <h1>Illustrations</h1>

    <ul class="paintingsListing">
      <% @illustrations.each_with_index do |painting, i| %>
      
          <li>        
            <a id="xtrigger" class="xtrig" rel="coda-slider-1" href="#<%= i += 1 %>">

              <%= cl_image_tag(painting.cloudinary_asset_id, quality: 90, width: 150, height: 150, crop: :fill) %>


              <div id="" class="paintingInfo">

                <h3><%= painting.title %></h3>

                <i><%= painting.body %></i>

                <span class="cop-order-info"><%= painting.ordering %></span>  

              </div>           

            </a> 
          </li>
      
      <% end %>
    </ul>

    <hr style="clear: both;"/>

  

<% if logged_in? %>
    <p>
    <%= link_to "Create a New Painting", new_painting_path, class: "new_painting" %>
    </p>                   
<% else %>

<% end %>









</div>

<div class="wrapper">
  <div class="container-hc">

    <noscript>
      <div>
            <p>Unfortunately your browser does not hava JavaScript capabilities which are required to exploit full functionality of our site. This could be the result of two possible scenarios:</p>
            <ol>
                <li>You are using an old web browser, in which case you should upgrade it to a newer version. We recommend the latest version of <a href="http://www.getfirefox.com">Firefox</a>.</li>
                <li>You have disabled JavaScript in you browser, in which case you will have to enable it to properly use our site. <a href="http://www.google.com/support/bin/answer.py?answer=23852">Learn how to enable JavaScript</a>.</li>
            </ol>
        </div>
    </noscript>






    <div id="art-gallery">
      <a href="#" id="slider-close" >Art Index</a> <br />


      <a href="#" id="slideShow" style="display :block;">Slideshow</a> 
      <a href="#" id="slideShowStop" style="display :none;" >Pause Slideshow</a> <br />

      <a href="#" id="slideBack"> < Back </a> 
      <a href="#" id="slideFront"> Front > </a> 

      <div id="slider" class="hc-slider-wrapper">
        <ul class="slides">

      <% @illustrations.each do |ill| %>
          <li class="slide">
            <div class="panel-wrapper">            
              <%= cl_image_tag(ill.cloudinary_asset_id, width: 500, height: 500, crop: :fit) %>
              <h2 id="title"><strong><%= ill.title %></strong> <%= ill.body %></h2>
           
            </div>
          </li>
      
      <% end %>
 
  
        </ul>
      </div>  

    </div>
  </div>
</div>

app/views/paintings/index-bu.html.erb
<% provide(:title, 'Paintings') %>

<h1>Paintings</h1>

  <div id="art-index" class="container">
    <div class="top">
      <a id="close">Gallery</a>
    </div>   

    <ul class="paintingsListing">
      <% @number = 0 %>
      <% @paintings.each do |painting| %>
      
          <li>        
            <a id="xtrigger" class="xtrig" rel="coda-slider-1" href="#<%= @number += 1 %>">
              <img src="<%= painting.image.url(:small) %>">
            </a>        
            <br />
            <%= link_to painting.title, painting_path(painting), 
            class: 'painting_title', 
            id: "painting_#{painting.id}" %> |
            <i><%= painting.body %></i>
            <span class="cop-order-info"><%= painting.ordering %></span>
            <br />
          </li>
      
      <% end %>
    </ul>

    <hr style="clear: both;"/>

    <h1>Comissions</h1>

    <ul class="paintingsListing">
      <% @numberNew = @number %>
      <% @paintings2.each do |painting| %>
      
          <li>        
            <a class="xtrig" rel="coda-slider-1" href="#<%= @numberNew += 1 %>">
              <img src="<%= painting.image.url(:small) %>">
            </a>        
            <br />
            <%= link_to painting.title, painting_path(painting), 
            class: 'painting_title', 
            id: "painting_#{painting.id}" %> |
            <i><%= painting.body %></i>
            <span class="cop-order-info"><%= painting.ordering %></span>
            <br />
            <%= painting.painting_featured %>
          </li>
      
      <% end %>
    </ul>

    <hr style="clear: both;"/>

    <p>
    <%= link_to "Create a New Painting", new_painting_path, class: "new_painting" %>
    </p>

</div>

<div class="wrapper">
  <div class="container">

    <noscript>
      <div>
            <p>Unfortunately your browser does not hava JavaScript capabilities which are required to exploit full functionality of our site. This could be the result of two possible scenarios:</p>
            <ol>
                <li>You are using an old web browser, in which case you should upgrade it to a newer version. We recommend the latest version of <a href="http://www.getfirefox.com">Firefox</a>.</li>
                <li>You have disabled JavaScript in you browser, in which case you will have to enable it to properly use our site. <a href="http://www.google.com/support/bin/answer.py?answer=23852">Learn how to enable JavaScript</a>.</li>
            </ol>
        </div>
    </noscript>






    <div id="art-gallery">
      <a id="slider-close" >Art Index</a>
      <div id="slider" class="coda-slider-wrapper">
        <div class="coda-slider preload" id="coda-slider-1">

      <% @paintingsFull.each do |painting| %>
      
          <div class="panel">
            <div class="panel-wrapper">            
              <img src="<%= painting.image.url(:large) %>">
              <h2 id="title"><strong><%= painting.title %></strong> <%= painting.body %></h2>
           
            </div>
          </div>
      
      <% end %>

      <% @paintingsFullNon.each do |painting| %>
      
          <div class="panel">
            <div class="panel-wrapper">            
              <img src="<%= painting.image.url(:large) %>">
              <h2 id="title"><strong><%= painting.title %></strong> <%= painting.body %></h2>   
            </div>
          </div>
      
      <% end %>      

        </div>  
      </div>
    </div>

  </div>
</div>

app/views/paintings/index.html.erb
<% provide(:title, 'Paintings') %>

<script type="text/javascript">
  $( "#Paintings-nav" ).css( "font-weight", "bold" );
</script>

  <div id="art-index" class="container">
    
      <a id="close">Gallery</a>
    

    <h1>Paintings</h1>

    <ul class="paintingsListing">
      <% @number = 0 %>
      <% @paintings.each do |painting| %>
      
          <li>        
            <a id="xtrigger" class="xtrig" rel="coda-slider-1" href="#<%= @number += 1 %>">

              <%= cl_image_tag(painting.cloudinary_asset_id, quality: 90, width: 150, height: 150, crop: :fill) %>


              <div id="" class="paintingInfo">

                <h3><%= painting.title %></h3>

                <i><%= painting.body %></i>

                <span class="cop-order-info"><%= painting.ordering %></span>  

              </div>           

            </a> 
          </li>
      
      <% end %>
    </ul>

    <hr style="clear: both;"/>

    <h1>Comissions</h1>

    <ul class="paintingsListing">
      <% @numberNew = @number %>
      <% @paintings2.each do |painting| %>
      
          <li>        
            <a id="xtrigger" class="xtrig" rel="coda-slider-1" href="#<%= @number += 1 %>">

              <%= cl_image_tag(painting.cloudinary_asset_id, quality: 90, width: 150, height: 150, crop: :fill) %>

              <div id="" class="paintingInfo">

                <h3><%= painting.title %></h3>

                <i><%= painting.body %></i>

                <span class="cop-order-info"><%= painting.ordering %></span>  

              </div>           

            </a> 
          </li>
      
      <% end %>
    </ul>

    <hr style="clear: both;"/>





<% if logged_in? %>
    <p>
    <%= link_to "Create a New Painting", new_painting_path, class: "new_painting" %>
    </p>                   
<% else %>

<% end %>









</div>

<div class="wrapper">
  <div class="container-hc">

    <noscript>
      <div>
            <p>Unfortunately your browser does not hava JavaScript capabilities which are required to exploit full functionality of our site. This could be the result of two possible scenarios:</p>
            <ol>
                <li>You are using an old web browser, in which case you should upgrade it to a newer version. We recommend the latest version of <a href="http://www.getfirefox.com">Firefox</a>.</li>
                <li>You have disabled JavaScript in you browser, in which case you will have to enable it to properly use our site. <a href="http://www.google.com/support/bin/answer.py?answer=23852">Learn how to enable JavaScript</a>.</li>
            </ol>
        </div>
    </noscript>






    <div id="art-gallery">
      <a href="#" id="slider-close" >Art Index</a> <br />


      <a href="#" id="slideShow" style="display :block;">Slideshow</a> 
      <a href="#" id="slideShowStop" style="display :none;" >Pause Slideshow</a> <br />

      <a href="#" id="slideBack"> < Back </a> 
      <a href="#" id="slideFront"> Front > </a> 

      <div id="slider" class="hc-slider-wrapper">
        <ul class="slides">

      <% @paintingsFull.each do |painting| %>
          <li class="slide">
            <div class="panel-wrapper">            
              <%= cl_image_tag(painting.cloudinary_asset_id) %>
              <h2 id="title"><strong><%= painting.title %></strong> <%= painting.body %></h2>
           
            </div>
          </li>
      
      <% end %>

      <% @paintingsFullNon.each do |painting| %>
      
          <li class="slide">
            <div class="panel-wrapper">            
              <%= cl_image_tag(painting.cloudinary_asset_id) %>
              <h2 id="title"><strong><%= painting.title %></strong> <%= painting.body %></h2>   
            </div>
          </li>
      
      <% end %>      

        </ul>
      </div>  

    </div>
  </div>
</div>

app/views/paintings/new.html.erb
<% provide(:title, 'Add A New Painting') %>
<h1>Create a New Paintning</h1>

<%= render partial: 'form' %>

app/views/paintings/order.html.erb
<% provide(:title, 'Paintings Order') %>

<h1>Paintings Order: <i>Refresh</i></h1>

  <div id="art-index" class="container"> 

    <ul class="">
      <% @number = 0 %>
      <% @paintings.each do |painting| %>
      
          <li>        
            <%= link_to painting.title, painting_path(painting), 
            class: 'painting_title', 
            id: "painting_#{painting.id}" %> |
            <i><%= painting.body %></i>
            <span id= "cop-order_num_<%= painting.id %>" class="cop-order-info"><%= painting.ordering %></span>
            <br />
            Featured: <%= painting.painting_featured %>

            <% if current_user.admin? %>
              | <%= link_to "delete", painting, method: :delete, data: { confirm: "You sure?" } %>
            <% end %>            
            
            <%= form_for (painting), remote: true do |f| %>
              <p>
                <%= f.label :ordering %><br />
                <%= f.text_field :ordering %>
                <span style="float: right;"><%= f.submit %></span>
              </p>
            <% end %>

          </li>

       
      <% end %>
    </ul>

    <hr style="clear: both;"/>

    <h1>Comissions</h1>

    <ul class="">
      <% @numberNew = @number %>
      <% @paintings2.each do |painting| %>
      
          <li>        
            <%= link_to painting.title, painting_path(painting), 
            class: 'painting_title', 
            id: "painting_#{painting.id}" %> |
            <i><%= painting.body %></i>
            <span id= "cop-order_num_<%= painting.id %>" class="cop-order-info"><%= painting.ordering %></span>
            <br />
            Featured: <%= painting.painting_featured %>

            <% if current_user.admin? %>
              | <%= link_to "delete", painting, method: :delete, data: { confirm: "You sure?" } %>
            <% end %>            
            
            <%= form_for (painting), remote: true do |f| %>
              <p>
                <%= f.label :ordering %><br />
                <%= f.text_field :ordering %>
                <span style="float: right;"><%= f.submit %></span>
              </p>
            <% end %>
          </li>
      
      <% end %>
    </ul>

    <hr style="clear: both;"/>

    <h1>Illustrations</h1>

    <ul class="">
      <% @numberNew = @number %>
      <% @illustrations.each do |painting| %>
      
          <li>        
            <%= link_to painting.title, painting_path(painting), 
            class: 'painting_title', 
            id: "painting_#{painting.id}" %> |
            <i><%= painting.body %></i>
            <span id= "cop-order_num_<%= painting.id %>" class="cop-order-info"><%= painting.ordering %></span>
            <br />
            Featured: <%= painting.painting_featured %>

            <% if current_user.admin? %>
              | <%= link_to "delete", painting, method: :delete, data: { confirm: "You sure?" } %>
            <% end %>            
            
            <%= form_for (painting), remote: true do |f| %>
              <p>
                <%= f.label :ordering %><br />
                <%= f.text_field :ordering %>
                <span style="float: right;"><%= f.submit %></span>
              </p>
            <% end %>
          </li>
      
      <% end %>
    </ul>

    <hr style="clear: both;"/>

    <p>
    <%= link_to "Create a New Painting", new_painting_path, class: "new_painting" %>
    </p>

</div>

app/views/paintings/show.html.erb
<h1><%= @painting.title %></h1>

<p><%= cl_image_tag(@painting.cloudinary_asset_id) %></p>
<p><%= @painting.body %></p>
<p>
  Tags:
  <% @painting.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %> |
  <i>Order:</i> <%= @painting.ordering %> | 
  <i>Type:</i> <%= @painting.painting_type %> | 
  <i>Featured:</i> <%= @painting.painting_featured %>

</p>

<%= link_to "<< Back to Paintings List", paintings_path %> |
<%= link_to "edit", edit_painting_path(@painting) %> |
<%= link_to "delete", painting_path(@painting), data: { confirm: "You sure?" }, method: :delete %>

app/views/paintings/update.js.erb
$("#cop-order_num_<%= @painting.id %>").html(''); 

$("#cop-order_num_<%= @painting.id %>").append( <%= @painting.ordering %> ); 