config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'music'   => 'static_pages#music'
  get 'video'   => 'static_pages#video'
  get 'signup'  => 'users#new'

  #get 'sample-artwork'  => 'paintings/2'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'paintings/order'   => 'paintings#order'
  resources :paintings

  get    'illustrations' => 'paintings#illustrations'

  get    'say-hello'   => 'contacts#new'
  resources :contacts

  resources :tags
  resources :users
  resources :account_activations, only: [:edit]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include ContactsHelper

	def index
		@contacts = Contact.all
	end

	def show
		@contact = Contact.find(params[:id])
	end

	def new
		@contact = Contact.new
	end

	def create
    	@contact = Contact.new(contact_params)
    	@contact.save

    	redirect_to action: "new"
    	flash[:success] = "Your contact has been recieved."

	end
end

app/helpers/contacts_helper.rb
module ContactsHelper

	def contact_params
	  params.require(:contact).permit(:name, :email, :message)
	end

end

app/views/contacts/index.html.erb
<% provide(:title, "Contacts Subitted") %>
<h1>All Contacts</h1>

<ul id="contacts">
  <% @contacts.each do |contact| %>
  	<li>
    	<div id="contactName">Name: <%= link_to contact.name, contact_path(contact), class: 'article_title' %></div>
    	<div id="contactName">Email: <%= contact.email %></div>
    	<div id="contactName">Message: <%= contact.message %></div>
    </li>
  <% end %>
</ul>

app/views/contacts/new.html.erb
<% provide(:title, "Submit a Contact") %>

<h1><span style="float: left; padding-right: 5px;"><%= image_tag("eye.png") %></span>Contact</h1>

<script type="text/javascript">
  $( "#Contact-nav" ).css( "font-weight", "bold" );
</script>

<%= form_for(@contact) do |f| %>
  <ul>
  <% @contact.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>  
  <p>
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </p>
  <p style="text-align: center;">
    <%= f.submit id: "hc_sub", value: "Send" %>
  </p>
<% end %>

app/views/contacts/show.html.erb
<% provide(:title, "Specific Contact Subitted") %>
<h1>This Contact: <i><%= @contact.name %></i></h1>


<p><%= @contact.email %></p>
<p><%= @contact.message %></p>
<%= link_to "<< Back to Contacts List", contacts_path %>
<%= link_to "delete", contact_path(@contact), data: { confirm: "You sure?" }, method: :delete %>