config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'music'   => 'static_pages#music'
  get 'video'   => 'static_pages#video'
  get 'signup'  => 'users#new'

  #get 'sample-artwork'  => 'paintings/2'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'paintings/order'   => 'paintings#order'
  resources :paintings

  get    'illustrations' => 'paintings#illustrations'

  get    'say-hello'   => 'contacts#new'
  resources :contacts

  resources :tags
  resources :users
  resources :account_activations, only: [:edit]

end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_many :taggings
	has_many :paintings, through: :taggings

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	
	before_action :logged_in_user, only: [ :destroy]
	before_action :admin_user,     only: [ :destroy]

	def index
	@tags = Tag.all
	end

	def show
		@tag = Tag.find(params[:id])
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy
		redirect_to action: "index"
	end

	private

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end  	

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<% provide(:title, 'Tags') %>
<h1>All Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
    	<p><%= link_to tag.name, tag_path(tag) %></p>
    </li>
  <% end %>
</ul>

<%= link_to "<< Back to Painting List", paintings_path %> | 

<a href="#">Delete All - Needs Help</a>

app/views/tags/show.html.erb
<% provide(:title, 'Tag') %>
<h1>Paintings Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.paintings.each do |painting| %>
    <li><%= link_to painting.title, painting_path(painting) %></li>
  <% end %>
</ul>

<%= link_to "<< Back to Tags List", tags_path %> | 

<% if logged_in? %>
<%= link_to "Delete This Tag", tag_path(@tag), method: :delete, data: {confirm: "Really delete the tag?"} %>
<% end %>
<br />

<%= link_to "<< Back to Paintings List", paintings_path %> 