config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'music'   => 'static_pages#music'
  get 'video'   => 'static_pages#video'
  get 'signup'  => 'users#new'

  #get 'sample-artwork'  => 'paintings/2'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'paintings/order'   => 'paintings#order'
  resources :paintings

  get    'illustrations' => 'paintings#illustrations'

  get    'say-hello'   => 'contacts#new'
  resources :contacts

  resources :tags
  resources :users
  resources :account_activations, only: [:edit]

end

app/views/layouts/_footer.html.erb
<footer class="footer">

<p style="float: left;">
    &copy; 2017 <a href="http://homelesscop.com/#">HomelessCop.com</a> | by <a href="https://historytrees.com/">Druzi on Rails</a>
</p>
 
  <nav>
    <ul>      
        <% if logged_in? %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Order Paintings", :controller => :paintings, :action => :order %></li>
              <li><%= link_to "Contacts from Website", contacts_path %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Users", users_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li><%= image_tag("eye.png") %></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="cop-navbar" class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("hc-logo.png", alt: "Homeless Cop Logo"), root_path, id: "logo" %>


   
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Paintings", paintings_path, id: "Paintings-nav" %></li>
        <li><%= link_to "Illustrations", illustrations_path, id: "Illustrations-nav" %></li>
        <li><%= link_to "Videos", video_path, id: "Videos-nav" %></li>
        <!-- <li><%= link_to "Music", music_path, id: "Music-nav" %></li> -->
        <li><a id="aboutpull">About</a></li>
        <li id="Contact-nav"><%= link_to "Contact", :controller => :contacts, :action => :new %></li>  
        <li><a href="http://homelesscop.bigcartel.com/" alt="Homeless Cop Big Cartel" target="_blank">Store</a></li>


      </ul>
    </nav>


<ul id="networks">
  
  <li id="instigram">
    <a href="https://www.instagram.com/homelesscop/" alt="Homeless Cop Instigram" target="_blank"></a>
  </li>

  <li id="twitter">
    <a href="https://twitter.com/homelesscop" alt="Homeless Cop Twitter" target="_blank"></a>
  </li>

  <li id="facebook">
    <a href="https://www.facebook.com/homelesscop " alt="Homeless Cop Facebook" target="_blank"></a>
  </li>

</ul>


  </div>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

    <link rel="shortcut icon" href="/assets/favicon.ico">
    <%= render 'layouts/shim' %>
  </head>

  <body class="<%= controller_name %>-body <%= action_name %>-body">

<div id="pulldown" class="wrapper">
  <div id="about" class="container">

        <div id="content" class="mod">

            <%= link_to image_tag("profile.jpg", alt: "Homeless Cop About"), root_path, id: "profile" %>

            <h2 style="color:#FF0;">Homeless Cop</h2>
<p>            The ultra crispy oil paintings of Homeless Cop are trying to have sex with your eyes. These candy colors and bold lines live and breathe out a crazy world of monsters and men, ghosts and Gods, and this all looks really, really cool. There are battles and epic moments taking place in another dimension, where style and integrity win kingdoms. Perhaps there is a secret story, but there is a mysteriously likeable universal appeal, and the attention to detail is noticeable. Homeless Cop works really hard on his paintings, and his biggest accomplishment so far has been getting his art on Adult Swim. "I've always painted things I like. People, places, and things. My whole life I've been drawing and painting, and I really feel like I was born to do this. I think my work evolves in terms of subject matter, but the execution just stays true to my style. My paintings look look like a robot made them, and I get a lot of pleasure being able to say I made them with my hands. My favorite artist is Jean-Michel Basquiat, and my favorite band is Nirvana. I also like pizza."</p>
            
<p>Homeless Cop (AKA: Jason Fennell) is an artist/musician who grew up in St. Louis, moved to Chicago for a long time, and currently lives downtown Indianapolis. He has no formal training or schooling. He is currently working on new collections and commissions, and playing drums in the instrumental-reggae-funk-rock group, Chemical Bomb Police.</p>

            <p><a href="/say-hello">Contact</a> Homeless Cop</p>
        </div>

        <a id="aboutclose" href="#">
          <%= image_tag("white.png", alt: "Close About Page") %>
        </a>


    </div>
    
</div>

<!-- End Hidden Items -->
    
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html>